////////////////////////////////////////////////////////////////////////////
//
//  VLiB Source File.
//  Copyright (C), V Studio, 2018-2024.
// -------------------------------------------------------------------------
//  File name:   tostr.cpp
//  Version:     v1.00
//  Created:     09/05/24 by Serial Designation V-X1.
//  Description: 
// -------------------------------------------------------------------------
//  History:
//
////////////////////////////////////////////////////////////////////////////

#include "tostr.h"
#include "openxr/openxr.h"
#include "vulkan/vulkan_core.h"

VLIBPP_START

#ifndef VLIB_REMOVE_TOSTR_FUNC

const wchar* vwstr_toStrXrType(i32 In) {
	switch(In){
		case (XR_TYPE_UNKNOWN):
			return U"XR_TYPE_UNKNOWN";
			break;
		case (XR_TYPE_API_LAYER_PROPERTIES):
			return U"XR_TYPE_API_LAYER_PROPERTIES";
			break;
		case (XR_TYPE_EXTENSION_PROPERTIES):
			return U"XR_TYPE_EXTENSION_PROPERTIES";
			break;
		case (XR_TYPE_INSTANCE_CREATE_INFO):
			return U"XR_TYPE_INSTANCE_CREATE_INFO";
			break;
		case (XR_TYPE_SYSTEM_GET_INFO):
			return U"XR_TYPE_SYSTEM_GET_INFO";
			break;
		case (XR_TYPE_SYSTEM_PROPERTIES):
			return U"XR_TYPE_SYSTEM_PROPERTIES";
			break;
		case (XR_TYPE_VIEW_LOCATE_INFO):
			return U"XR_TYPE_VIEW_LOCATE_INFO";
			break;
		case (XR_TYPE_VIEW):
			return U"XR_TYPE_VIEW";
			break;
		case (XR_TYPE_SESSION_CREATE_INFO):
			return U"XR_TYPE_SESSION_CREATE_INFO";
			break;
		case (XR_TYPE_SWAPCHAIN_CREATE_INFO):
			return U"XR_TYPE_SWAPCHAIN_CREATE_INFO";
			break;
		case (XR_TYPE_SESSION_BEGIN_INFO):
			return U"XR_TYPE_SESSION_BEGIN_INFO";
			break;
		case (XR_TYPE_VIEW_STATE):
			return U"XR_TYPE_VIEW_STATE";
			break;
		case (XR_TYPE_FRAME_END_INFO):
			return U"XR_TYPE_FRAME_END_INFO";
			break;
		case (XR_TYPE_HAPTIC_VIBRATION):
			return U"XR_TYPE_HAPTIC_VIBRATION";
			break;
		case (XR_TYPE_EVENT_DATA_BUFFER):
			return U"XR_TYPE_EVENT_DATA_BUFFER";
			break;
		case (XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING):
			return U"XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING";
			break;
		case (XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED):
			return U"XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED";
			break;
		case (XR_TYPE_ACTION_STATE_BOOLEAN):
			return U"XR_TYPE_ACTION_STATE_BOOLEAN";
			break;
		case (XR_TYPE_ACTION_STATE_FLOAT):
			return U"XR_TYPE_ACTION_STATE_FLOAT";
			break;
		case (XR_TYPE_ACTION_STATE_VECTOR2F):
			return U"XR_TYPE_ACTION_STATE_VECTOR2F";
			break;
		case (XR_TYPE_ACTION_STATE_POSE):
			return U"XR_TYPE_ACTION_STATE_POSE";
			break;
		case (XR_TYPE_ACTION_SET_CREATE_INFO):
			return U"XR_TYPE_ACTION_SET_CREATE_INFO";
			break;
		case (XR_TYPE_ACTION_CREATE_INFO):
			return U"XR_TYPE_ACTION_CREATE_INFO";
			break;
		case (XR_TYPE_INSTANCE_PROPERTIES):
			return U"XR_TYPE_INSTANCE_PROPERTIES";
			break;
		case (XR_TYPE_FRAME_WAIT_INFO):
			return U"XR_TYPE_FRAME_WAIT_INFO";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_PROJECTION):
			return U"XR_TYPE_COMPOSITION_LAYER_PROJECTION";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_QUAD):
			return U"XR_TYPE_COMPOSITION_LAYER_QUAD";
			break;
		case (XR_TYPE_REFERENCE_SPACE_CREATE_INFO):
			return U"XR_TYPE_REFERENCE_SPACE_CREATE_INFO";
			break;
		case (XR_TYPE_ACTION_SPACE_CREATE_INFO):
			return U"XR_TYPE_ACTION_SPACE_CREATE_INFO";
			break;
		case (XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING):
			return U"XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING";
			break;
		case (XR_TYPE_VIEW_CONFIGURATION_VIEW):
			return U"XR_TYPE_VIEW_CONFIGURATION_VIEW";
			break;
		case (XR_TYPE_SPACE_LOCATION):
			return U"XR_TYPE_SPACE_LOCATION";
			break;
		case (XR_TYPE_SPACE_VELOCITY):
			return U"XR_TYPE_SPACE_VELOCITY";
			break;
		case (XR_TYPE_FRAME_STATE):
			return U"XR_TYPE_FRAME_STATE";
			break;
		case (XR_TYPE_VIEW_CONFIGURATION_PROPERTIES):
			return U"XR_TYPE_VIEW_CONFIGURATION_PROPERTIES";
			break;
		case (XR_TYPE_FRAME_BEGIN_INFO):
			return U"XR_TYPE_FRAME_BEGIN_INFO";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW):
			return U"XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW";
			break;
		case (XR_TYPE_EVENT_DATA_EVENTS_LOST):
			return U"XR_TYPE_EVENT_DATA_EVENTS_LOST";
			break;
		case (XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING):
			return U"XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING";
			break;
		case (XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED):
			return U"XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED";
			break;
		case (XR_TYPE_INTERACTION_PROFILE_STATE):
			return U"XR_TYPE_INTERACTION_PROFILE_STATE";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO";
			break;
		case (XR_TYPE_ACTION_STATE_GET_INFO):
			return U"XR_TYPE_ACTION_STATE_GET_INFO";
			break;
		case (XR_TYPE_HAPTIC_ACTION_INFO):
			return U"XR_TYPE_HAPTIC_ACTION_INFO";
			break;
		case (XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO):
			return U"XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO";
			break;
		case (XR_TYPE_ACTIONS_SYNC_INFO):
			return U"XR_TYPE_ACTIONS_SYNC_INFO";
			break;
		case (XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO):
			return U"XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO";
			break;
		case (XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO):
			return U"XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_CUBE_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_CUBE_KHR";
			break;
		case (XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR):
			return U"XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR";
			break;
		case (XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR):
			return U"XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR";
			break;
		case (XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT):
			return U"XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR";
			break;
		case (XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT):
			return U"XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT";
			break;
		case (XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT):
			return U"XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT";
			break;
		case (XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT):
			return U"XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT";
			break;
		case (XR_TYPE_DEBUG_UTILS_LABEL_EXT):
			return U"XR_TYPE_DEBUG_UTILS_LABEL_EXT";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR";
			break;
		case (XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR):
			return U"XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR";
			break;
		case (XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR):
			return U"XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR or XR_TYPE_GRAPHICS_BINDING_VULKAN2_KHR";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR or XR_TYPE_SWAPCHAIN_IMAGE_VULKAN2_KHR";
			break;
		case (XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR):
			return U"XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR or XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN2_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_D3D11_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_D3D11_KHR";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR";
			break;
		case (XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR):
			return U"XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_D3D12_KHR):
			return U"XR_TYPE_GRAPHICS_BINDING_D3D12_KHR";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR";
			break;
		case (XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR):
			return U"XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR";
			break;
		case (XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT):
			return U"XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT";
			break;
		case (XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT):
			return U"XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT";
			break;
		case (XR_TYPE_VISIBILITY_MASK_KHR):
			return U"XR_TYPE_VISIBILITY_MASK_KHR";
			break;
		case (XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR):
			return U"XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR";
			break;
		case (XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX):
			return U"XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX";
			break;
		case (XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX):
			return U"XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB";
			break;
		case (XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT):
			return U"XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT";
			break;
		case (XR_TYPE_GRAPHICS_BINDING_EGL_MNDX):
			return U"XR_TYPE_GRAPHICS_BINDING_EGL_MNDX";
			break;
		case (XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT";
			break;
		case (XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT):
			return U"XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT";
			break;
		case (XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT):
			return U"XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT";
			break;
		case (XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT):
			return U"XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT";
			break;
		case (XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT):
			return U"XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT";
			break;
		case (XR_TYPE_HAND_JOINT_LOCATIONS_EXT):
			return U"XR_TYPE_HAND_JOINT_LOCATIONS_EXT";
			break;
		case (XR_TYPE_HAND_JOINT_VELOCITIES_EXT):
			return U"XR_TYPE_HAND_JOINT_VELOCITIES_EXT";
			break;
		case (XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT):
			return U"XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT";
			break;
		case (XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT):
			return U"XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT):
			return U"XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT";
			break;
		case (XR_TYPE_HAND_MESH_MSFT):
			return U"XR_TYPE_HAND_MESH_MSFT";
			break;
		case (XR_TYPE_HAND_POSE_TYPE_INFO_MSFT):
			return U"XR_TYPE_HAND_POSE_TYPE_INFO_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT";
			break;
		case (XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT):
			return U"XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT):
			return U"XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT";
			break;
		case (XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT):
			return U"XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT";
			break;
		case (XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT):
			return U"XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT";
			break;
		case (XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT):
			return U"XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT";
			break;
		case (XR_TYPE_CONTROLLER_MODEL_STATE_MSFT):
			return U"XR_TYPE_CONTROLLER_MODEL_STATE_MSFT";
			break;
		case (XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC):
			return U"XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC";
			break;
		case (XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT):
			return U"XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT):
			return U"XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT):
			return U"XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT";
			break;
		case (XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB):
			return U"XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB";
			break;
		case (XR_TYPE_BODY_TRACKER_CREATE_INFO_FB):
			return U"XR_TYPE_BODY_TRACKER_CREATE_INFO_FB";
			break;
		case (XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB):
			return U"XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB";
			break;
		case (XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB";
			break;
		case (XR_TYPE_BODY_JOINT_LOCATIONS_FB):
			return U"XR_TYPE_BODY_JOINT_LOCATIONS_FB";
			break;
		case (XR_TYPE_BODY_SKELETON_FB):
			return U"XR_TYPE_BODY_SKELETON_FB";
			break;
		case (XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT):
			return U"XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT";
			break;
		case (XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE):
			return U"XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE";
			break;
		case (XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT):
			return U"XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT";
			break;
		case (XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR):
			return U"XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR";
			break;
		case (XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR):
			return U"XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR";
			break;
		case (XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR):
			return U"XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR";
			break;
		case (XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR):
			return U"XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR):
			return U"XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR";
			break;
		case (XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT):
			return U"XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_CREATE_INFO_MSFT):
			return U"XR_TYPE_SCENE_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT):
			return U"XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT";
			break;
		case (XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT):
			return U"XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_COMPONENTS_MSFT):
			return U"XR_TYPE_SCENE_COMPONENTS_MSFT";
			break;
		case (XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT):
			return U"XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT):
			return U"XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT";
			break;
		case (XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT):
			return U"XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_OBJECTS_MSFT):
			return U"XR_TYPE_SCENE_OBJECTS_MSFT";
			break;
		case (XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT):
			return U"XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT):
			return U"XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_PLANES_MSFT):
			return U"XR_TYPE_SCENE_PLANES_MSFT";
			break;
		case (XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT):
			return U"XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_MESHES_MSFT):
			return U"XR_TYPE_SCENE_MESHES_MSFT";
			break;
		case (XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT):
			return U"XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_MESH_BUFFERS_MSFT):
			return U"XR_TYPE_SCENE_MESH_BUFFERS_MSFT";
			break;
		case (XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT):
			return U"XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT";
			break;
		case (XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT):
			return U"XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT";
			break;
		case (XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT):
			return U"XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT";
			break;
		case (XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT):
			return U"XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT):
			return U"XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT";
			break;
		case (XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB):
			return U"XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB";
			break;
		case (XR_TYPE_VIVE_TRACKER_PATHS_HTCX):
			return U"XR_TYPE_VIVE_TRACKER_PATHS_HTCX";
			break;
		case (XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX):
			return U"XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX";
			break;
		case (XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC):
			return U"XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC";
			break;
		case (XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC):
			return U"XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC";
			break;
		case (XR_TYPE_FACIAL_EXPRESSIONS_HTC):
			return U"XR_TYPE_FACIAL_EXPRESSIONS_HTC";
			break;
		case (XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB";
			break;
		case (XR_TYPE_HAND_TRACKING_MESH_FB):
			return U"XR_TYPE_HAND_TRACKING_MESH_FB";
			break;
		case (XR_TYPE_HAND_TRACKING_SCALE_FB):
			return U"XR_TYPE_HAND_TRACKING_SCALE_FB";
			break;
		case (XR_TYPE_HAND_TRACKING_AIM_STATE_FB):
			return U"XR_TYPE_HAND_TRACKING_AIM_STATE_FB";
			break;
		case (XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB):
			return U"XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB";
			break;
		case (XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB):
			return U"XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB";
			break;
		case (XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB):
			return U"XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB";
			break;
		case (XR_TYPE_SPACE_COMPONENT_STATUS_FB):
			return U"XR_TYPE_SPACE_COMPONENT_STATUS_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB";
			break;
		case (XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB):
			return U"XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB):
			return U"XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB):
			return U"XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB";
			break;
		case (XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB):
			return U"XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB";
			break;
		case (XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB):
			return U"XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB";
			break;
		case (XR_TYPE_KEYBOARD_TRACKING_QUERY_FB):
			return U"XR_TYPE_KEYBOARD_TRACKING_QUERY_FB";
			break;
		case (XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB";
			break;
		case (XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB):
			return U"XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB";
			break;
		case (XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_CREATE_INFO_FB):
			return U"XR_TYPE_PASSTHROUGH_CREATE_INFO_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB):
			return U"XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB";
			break;
		case (XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB):
			return U"XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB";
			break;
		case (XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB):
			return U"XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB";
			break;
		case (XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB):
			return U"XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_STYLE_FB):
			return U"XR_TYPE_PASSTHROUGH_STYLE_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB):
			return U"XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB):
			return U"XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB):
			return U"XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB";
			break;
		case (XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB):
			return U"XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB";
			break;
		case (XR_TYPE_RENDER_MODEL_PATH_INFO_FB):
			return U"XR_TYPE_RENDER_MODEL_PATH_INFO_FB";
			break;
		case (XR_TYPE_RENDER_MODEL_PROPERTIES_FB):
			return U"XR_TYPE_RENDER_MODEL_PROPERTIES_FB";
			break;
		case (XR_TYPE_RENDER_MODEL_BUFFER_FB):
			return U"XR_TYPE_RENDER_MODEL_BUFFER_FB";
			break;
		case (XR_TYPE_RENDER_MODEL_LOAD_INFO_FB):
			return U"XR_TYPE_RENDER_MODEL_LOAD_INFO_FB";
			break;
		case (XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB";
			break;
		case (XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB):
			return U"XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB";
			break;
		case (XR_TYPE_BINDING_MODIFICATIONS_KHR):
			return U"XR_TYPE_BINDING_MODIFICATIONS_KHR";
			break;
		case (XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO):
			return U"XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO";
			break;
		case (XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO):
			return U"XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO";
			break;
		case (XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO):
			return U"XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO):
			return U"XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO";
			break;
		case (XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO):
			return U"XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO";
			break;
		case (XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO):
			return U"XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO";
			break;
		case (XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO):
			return U"XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO";
			break;
		case (XR_TYPE_FRAME_END_INFO_ML):
			return U"XR_TYPE_FRAME_END_INFO_MU";
			break;
		case (XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_ML):
			return U"XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_MU";
			break;
		case (XR_TYPE_COORDINATE_SPACE_CREATE_INFO_ML):
			return U"XR_TYPE_COORDINATE_SPACE_CREATE_INFO_MU";
			break;
		case (XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML):
			return U"XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_CREATE_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_CREATE_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_SIZE_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_SIZE_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_ML):
			return U"XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_MU";
			break;
		case (XR_TYPE_MARKER_DETECTOR_STATE_ML):
			return U"XR_TYPE_MARKER_DETECTOR_STATE_MU";
			break;
		case (XR_TYPE_MARKER_SPACE_CREATE_INFO_ML):
			return U"XR_TYPE_MARKER_SPACE_CREATE_INFO_MU";
			break;
		case (XR_TYPE_LOCALIZATION_MAP_ML):
			return U"XR_TYPE_LOCALIZATION_MAP_MU";
			break;
		case (XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_ML):
			return U"XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_MU";
			break;
		case (XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_ML):
			return U"XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_MU";
			break;
		case (XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_ML):
			return U"XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_MU";
			break;
		case (XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_ML):
			return U"XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_MU";
			break;
		case (XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_ML):
			return U"XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_MU";
			break;
		case (XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_ML):
			return U"XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_MU";
			break;
		case (XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_ML):
			return U"XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_MU";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT):
			return U"XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT";
			break;
		case (XR_TYPE_SCENE_MARKERS_MSFT):
			return U"XR_TYPE_SCENE_MARKERS_MSFT";
			break;
		case (XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT):
			return U"XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT";
			break;
		case (XR_TYPE_SCENE_MARKER_QR_CODES_MSFT):
			return U"XR_TYPE_SCENE_MARKER_QR_CODES_MSFT";
			break;
		case (XR_TYPE_SPACE_QUERY_INFO_FB):
			return U"XR_TYPE_SPACE_QUERY_INFO_FB";
			break;
		case (XR_TYPE_SPACE_QUERY_RESULTS_FB):
			return U"XR_TYPE_SPACE_QUERY_RESULTS_FB";
			break;
		case (XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB):
			return U"XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB";
			break;
		case (XR_TYPE_SPACE_UUID_FILTER_INFO_FB):
			return U"XR_TYPE_SPACE_UUID_FILTER_INFO_FB";
			break;
		case (XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB):
			return U"XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB";
			break;
		case (XR_TYPE_SPACE_SAVE_INFO_FB):
			return U"XR_TYPE_SPACE_SAVE_INFO_FB";
			break;
		case (XR_TYPE_SPACE_ERASE_INFO_FB):
			return U"XR_TYPE_SPACE_ERASE_INFO_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB):
			return U"XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB):
			return U"XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB):
			return U"XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB";
			break;
		case (XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB):
			return U"XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB";
			break;
		case (XR_TYPE_SPACE_SHARE_INFO_FB):
			return U"XR_TYPE_SPACE_SHARE_INFO_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB";
			break;
		case (XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB";
			break;
		case (XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB):
			return U"XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB";
			break;
		case (XR_TYPE_SEMANTIC_LABELS_FB):
			return U"XR_TYPE_SEMANTIC_LABELS_FB";
			break;
		case (XR_TYPE_ROOM_LAYOUT_FB):
			return U"XR_TYPE_ROOM_LAYOUT_FB";
			break;
		case (XR_TYPE_BOUNDARY_2D_FB):
			return U"XR_TYPE_BOUNDARY_2D_FB";
			break;
		case (XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB):
			return U"XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB";
			break;
		case (XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE):
			return U"XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE";
			break;
		case (XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB";
			break;
		case (XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB):
			return U"XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB";
			break;
		case (XR_TYPE_SPACE_CONTAINER_FB):
			return U"XR_TYPE_SPACE_CONTAINER_FB";
			break;
		case (XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META):
			return U"XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META";
			break;
		case (XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META):
			return U"XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META";
			break;
		case (XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META):
			return U"XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META";
			break;
		case (XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB";
			break;
		case (XR_TYPE_FACE_TRACKER_CREATE_INFO_FB):
			return U"XR_TYPE_FACE_TRACKER_CREATE_INFO_FB";
			break;
		case (XR_TYPE_FACE_EXPRESSION_INFO_FB):
			return U"XR_TYPE_FACE_EXPRESSION_INFO_FB";
			break;
		case (XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB):
			return U"XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB";
			break;
		case (XR_TYPE_EYE_TRACKER_CREATE_INFO_FB):
			return U"XR_TYPE_EYE_TRACKER_CREATE_INFO_FB";
			break;
		case (XR_TYPE_EYE_GAZES_INFO_FB):
			return U"XR_TYPE_EYE_GAZES_INFO_FB";
			break;
		case (XR_TYPE_EYE_GAZES_FB):
			return U"XR_TYPE_EYE_GAZES_FB";
			break;
		case (XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB):
			return U"XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB):
			return U"XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB";
			break;
		case (XR_TYPE_HAPTIC_PCM_VIBRATION_FB):
			return U"XR_TYPE_HAPTIC_PCM_VIBRATION_FB";
			break;
		case (XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB):
			return U"XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB or XR_TYPE_DEVICE_PCM_SAMPLE_RATE_GET_INFO_FB";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB):
			return U"XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB";
			break;
		case (XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META):
			return U"XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META";
			break;
		case (XR_TYPE_PASSTHROUGH_PREFERENCES_META):
			return U"XR_TYPE_PASSTHROUGH_PREFERENCES_META";
			break;
		case (XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META):
			return U"XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META";
			break;
		case (XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META):
			return U"XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META";
			break;
		case (XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META):
			return U"XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META";
			break;
		case (XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META):
			return U"XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META";
			break;
		case (XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META):
			return U"XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META";
			break;
		case (XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META):
			return U"XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META";
			break;
		case (XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META):
			return U"XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META";
			break;
		case (XR_TYPE_EXTERNAL_CAMERA_OCULUS):
			return U"XR_TYPE_EXTERNAL_CAMERA_OCULUS";
			break;
		case (XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META):
			return U"XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META";
			break;
		case (XR_TYPE_PERFORMANCE_METRICS_STATE_META):
			return U"XR_TYPE_PERFORMANCE_METRICS_STATE_META";
			break;
		case (XR_TYPE_PERFORMANCE_METRICS_COUNTER_META):
			return U"XR_TYPE_PERFORMANCE_METRICS_COUNTER_META";
			break;
		case (XR_TYPE_SPACE_LIST_SAVE_INFO_FB):
			return U"XR_TYPE_SPACE_LIST_SAVE_INFO_FB";
			break;
		case (XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB):
			return U"XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB";
			break;
		case (XR_TYPE_SPACE_USER_CREATE_INFO_FB):
			return U"XR_TYPE_SPACE_USER_CREATE_INFO_FB";
			break;
		case (XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META):
			return U"XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META";
			break;
		case (XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META):
			return U"XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META";
			break;
		case (XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META):
			return U"XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META";
			break;
		case (XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META):
			return U"XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META):
			return U"XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META):
			return U"XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META):
			return U"XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META):
			return U"XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META";
			break;
		case (XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META):
			return U"XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META";
			break;
		case (XR_TYPE_SPACE_TRIANGLE_MESH_META):
			return U"XR_TYPE_SPACE_TRIANGLE_MESH_META";
			break;
		case (XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB):
			return U"XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB";
			break;
		case (XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB):
			return U"XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB";
			break;
		case (XR_TYPE_FACE_EXPRESSION_INFO2_FB):
			return U"XR_TYPE_FACE_EXPRESSION_INFO2_FB";
			break;
		case (XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB):
			return U"XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB";
			break;
		case (XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC):
			return U"XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC";
			break;
		case (XR_TYPE_PASSTHROUGH_COLOR_HTC):
			return U"XR_TYPE_PASSTHROUGH_COLOR_HTC";
			break;
		case (XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC):
			return U"XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC";
			break;
		case (XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC):
			return U"XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC";
			break;
		case (XR_TYPE_FOVEATION_APPLY_INFO_HTC):
			return U"XR_TYPE_FOVEATION_APPLY_INFO_HTC";
			break;
		case (XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC):
			return U"XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC";
			break;
		case (XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC):
			return U"XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC";
			break;
		case (XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC):
			return U"XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC";
			break;
		case (XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC):
			return U"XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC";
			break;
		case (XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT):
			return U"XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT";
			break;
		case (XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX):
			return U"XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX";
			break;
		case (XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX):
			return U"XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX";
			break;
		case (XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT):
			return U"XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT";
			break;
		case (XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT):
			return U"XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_LOCATION_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_LOCATION_EXT";
			break;
		case (XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT):
			return U"XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT";
			break;
		case (XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT):
			return U"XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT";
			break;
		case (XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT):
			return U"XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT";
			break;
		case (XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT):
			return U"XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT";
			break;
		case (XR_STRUCTURE_TYPE_MAX_ENUM):
			return U"XR_STRUCTURE_TYPE_MAX_ENUM";
			break;

		default:
			return U"XrStructureType_tostr_error";

	}

}

const wchar* vwstr_toStrXrResult(i32 In) {
	switch (In) {
		case(XR_SUCCESS):
			return U"XR_SUCCESS";
			break;
		case(XR_TIMEOUT_EXPIRED):
			return U"XR_TIMEOUT_EXPIRED";
			break;
		case(XR_SESSION_LOSS_PENDING):
			return U"XR_SESSION_LOSS_PENDING";
			break;
		case(XR_EVENT_UNAVAILABLE):
			return U"XR_EVENT_UNAVAILABLE";
			break;
		case(XR_SPACE_BOUNDS_UNAVAILABLE):
			return U"XR_SPACE_BOUNDS_UNAVAILABLE";
			break;
		case(XR_SESSION_NOT_FOCUSED):
			return U"XR_SESSION_NOT_FOCUSED";
			break;
		case(XR_FRAME_DISCARDED):
			return U"XR_FRAME_DISCARDED";
			break;
		case(XR_ERROR_VALIDATION_FAILURE):
			return U"XR_ERROR_VALIDATION_FAILURE";
			break;
		case(XR_ERROR_RUNTIME_FAILURE):
			return U"XR_ERROR_RUNTIME_FAILURE";
			break;
		case(XR_ERROR_OUT_OF_MEMORY):
			return U"XR_ERROR_OUT_OF_MEMORY";
			break;
		case(XR_ERROR_API_VERSION_UNSUPPORTED):
			return U"XR_ERROR_API_VERSION_UNSUPPORTED";
			break;
		case(XR_ERROR_INITIALIZATION_FAILED):
			return U"XR_ERROR_INITIALIZATION_FAILED";
			break;
		case(XR_ERROR_FUNCTION_UNSUPPORTED):
			return U"XR_ERROR_FUNCTION_UNSUPPORTED";
			break;
		case(XR_ERROR_FEATURE_UNSUPPORTED):
			return U"XR_ERROR_FEATURE_UNSUPPORTED";
			break;
		case(XR_ERROR_EXTENSION_NOT_PRESENT):
			return U"XR_ERROR_EXTENSION_NOT_PRESENT";
			break;
		case(XR_ERROR_LIMIT_REACHED):
			return U"XR_ERROR_LIMIT_REACHED";
			break;
		case(XR_ERROR_SIZE_INSUFFICIENT):
			return U"XR_ERROR_SIZE_INSUFFICIENT";
			break;
		case(XR_ERROR_HANDLE_INVALID):
			return U"XR_ERROR_HANDLE_INVALID";
			break;
		case(XR_ERROR_INSTANCE_LOST):
			return U"XR_ERROR_INSTANCE_LOST";
			break;
		case(XR_ERROR_SESSION_RUNNING):
			return U"XR_ERROR_SESSION_RUNNING";
			break;
		case(XR_ERROR_SESSION_NOT_RUNNING):
			return U"XR_ERROR_SESSION_NOT_RUNNING";
			break;
		case(XR_ERROR_SESSION_LOST):
			return U"XR_ERROR_SESSION_LOST";
			break;
		case(XR_ERROR_SYSTEM_INVALID):
			return U"XR_ERROR_SYSTEM_INVALID";
			break;
		case(XR_ERROR_PATH_INVALID):
			return U"XR_ERROR_PATH_INVALID";
			break;
		case(XR_ERROR_PATH_COUNT_EXCEEDED):
			return U"XR_ERROR_PATH_COUNT_EXCEEDED";
			break;
		case(XR_ERROR_PATH_FORMAT_INVALID):
			return U"XR_ERROR_PATH_FORMAT_INVALID";
			break;
		case(XR_ERROR_PATH_UNSUPPORTED):
			return U"XR_ERROR_PATH_UNSUPPORTED";
			break;
		case(XR_ERROR_LAYER_INVALID):
			return U"XR_ERROR_LAYER_INVALID";
			break;
		case(XR_ERROR_LAYER_LIMIT_EXCEEDED):
			return U"XR_ERROR_LAYER_LIMIT_EXCEEDED";
			break;
		case(XR_ERROR_SWAPCHAIN_RECT_INVALID):
			return U"XR_ERROR_SWAPCHAIN_RECT_INVALID";
			break;
		case(XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED):
			return U"XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED";
			break;
		case(XR_ERROR_ACTION_TYPE_MISMATCH):
			return U"XR_ERROR_ACTION_TYPE_MISMATCH";
			break;
		case(XR_ERROR_SESSION_NOT_READY):
			return U"XR_ERROR_SESSION_NOT_READY";
			break;
		case(XR_ERROR_SESSION_NOT_STOPPING):
			return U"XR_ERROR_SESSION_NOT_STOPPING";
			break;
		case(XR_ERROR_TIME_INVALID):
			return U"XR_ERROR_TIME_INVALID";
			break;
		case(XR_ERROR_REFERENCE_SPACE_UNSUPPORTED):
			return U"XR_ERROR_REFERENCE_SPACE_UNSUPPORTED";
			break;
		case(XR_ERROR_FILE_ACCESS_ERROR):
			return U"XR_ERROR_FILE_ACCESS_ERROR";
			break;
		case(XR_ERROR_FILE_CONTENTS_INVALID):
			return U"XR_ERROR_FILE_CONTENTS_INVALID";
			break;
		case(XR_ERROR_FORM_FACTOR_UNSUPPORTED):
			return U"XR_ERROR_FORM_FACTOR_UNSUPPORTED";
			break;
		case(XR_ERROR_FORM_FACTOR_UNAVAILABLE):
			return U"XR_ERROR_FORM_FACTOR_UNAVAILABLE";
			break;
		case(XR_ERROR_API_LAYER_NOT_PRESENT):
			return U"XR_ERROR_API_LAYER_NOT_PRESENT";
			break;
		case(XR_ERROR_CALL_ORDER_INVALID):
			return U"XR_ERROR_CALL_ORDER_INVALID";
			break;
		case(XR_ERROR_GRAPHICS_DEVICE_INVALID):
			return U"XR_ERROR_GRAPHICS_DEVICE_INVALID";
			break;
		case(XR_ERROR_POSE_INVALID):
			return U"XR_ERROR_POSE_INVALID";
			break;
		case(XR_ERROR_INDEX_OUT_OF_RANGE):
			return U"XR_ERROR_INDEX_OUT_OF_RANGE";
			break;
		case(XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED):
			return U"XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED";
			break;
		case(XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED):
			return U"XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED";
			break;
		case(XR_ERROR_NAME_DUPLICATED):
			return U"XR_ERROR_NAME_DUPLICATED";
			break;
		case(XR_ERROR_NAME_INVALID):
			return U"XR_ERROR_NAME_INVALID";
			break;
		case(XR_ERROR_ACTIONSET_NOT_ATTACHED):
			return U"XR_ERROR_ACTIONSET_NOT_ATTACHED";
			break;
		case(XR_ERROR_ACTIONSETS_ALREADY_ATTACHED):
			return U"XR_ERROR_ACTIONSETS_ALREADY_ATTACHED";
			break;
		case(XR_ERROR_LOCALIZED_NAME_DUPLICATED):
			return U"XR_ERROR_LOCALIZED_NAME_DUPLICATED";
			break;
		case(XR_ERROR_LOCALIZED_NAME_INVALID):
			return U"XR_ERROR_LOCALIZED_NAME_INVALID";
			break;
		case(XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING):
			return U"XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING";
			break;
		case(XR_ERROR_RUNTIME_UNAVAILABLE):
			return U"XR_ERROR_RUNTIME_UNAVAILABLE";
			break;
		case(XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR):
			return U"XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR";
			break;
		case(XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR):
			return U"XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR";
			break;
		case(XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT):
			return U"XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT";
			break;
		case(XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT):
			return U"XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT";
			break;
		case(XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT):
			return U"XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT";
			break;
		case(XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT):
			return U"XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT";
			break;
		case(XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT):
			return U"XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT";
			break;
		case(XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT):
			return U"XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT";
			break;
		case(XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT):
			return U"XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT";
			break;
		case(XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT):
			return U"XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT";
			break;
		case(XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT):
			return U"XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT";
			break;
		case(XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT):
			return U"XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT";
			break;
		case(XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB):
			return U"XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB";
			break;
		case(XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB):
			return U"XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB";
			break;
		case(XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB):
			return U"XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB";
			break;
		case(XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB):
			return U"XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB";
			break;
		case(XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB):
			return U"XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB";
			break;
		case(XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB):
			return U"XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB";
			break;
		case(XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB):
			return U"XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB):
			return U"XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB):
			return U"XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB):
			return U"XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB):
			return U"XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_UNKNOWN_PASSTHROUGH_FB):
			return U"XR_ERROR_UNKNOWN_PASSTHROUGH_FB";
			break;
		case(XR_ERROR_RENDER_MODEL_KEY_INVALID_FB):
			return U"XR_ERROR_RENDER_MODEL_KEY_INVALID_FB";
			break;
		case(XR_RENDER_MODEL_UNAVAILABLE_FB):
			return U"XR_RENDER_MODEL_UNAVAILABLE_FB";
			break;
		case(XR_ERROR_MARKER_NOT_TRACKED_VARJO):
			return U"XR_ERROR_MARKER_NOT_TRACKED_VARJO";
			break;
		case(XR_ERROR_MARKER_ID_INVALID_VARJO):
			return U"XR_ERROR_MARKER_ID_INVALID_VARJO";
			break;
		case(XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML):
			return U"XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_MU";
			break;
		case(XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML):
			return U"XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_MU";
			break;
		case(XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML):
			return U"XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_MU";
			break;
		case(XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML):
			return U"XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_MU";
			break;
		case(XR_ERROR_MARKER_INVALID_ML):
			return U"XR_ERROR_MARKER_INVALID_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_FAIL_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_FAIL_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_MU";
			break;
		case(XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML):
			return U"XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_MU";
			break;
		case(XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT):
			return U"XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT";
			break;
		case(XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT):
			return U"XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT";
			break;
		case(XR_SCENE_MARKER_DATA_NOT_STRING_MSFT):
			return U"XR_SCENE_MARKER_DATA_NOT_STRING_MSFT";
			break;
		case(XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB):
			return U"XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB";
			break;
		case(XR_ERROR_SPACE_LOCALIZATION_FAILED_FB):
			return U"XR_ERROR_SPACE_LOCALIZATION_FAILED_FB";
			break;
		case(XR_ERROR_SPACE_NETWORK_TIMEOUT_FB):
			return U"XR_ERROR_SPACE_NETWORK_TIMEOUT_FB";
			break;
		case(XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB):
			return U"XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB";
			break;
		case(XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB):
			return U"XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB";
			break;
		case(XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META):
			return U"XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META";
			break;
		case(XR_ERROR_HINT_ALREADY_SET_QCOM):
			return U"XR_ERROR_HINT_ALREADY_SET_QCOM";
			break;
		case(XR_ERROR_NOT_AN_ANCHOR_HTC):
			return U"XR_ERROR_NOT_AN_ANCHOR_HTC";
			break;
		case(XR_ERROR_SPACE_NOT_LOCATABLE_EXT):
			return U"XR_ERROR_SPACE_NOT_LOCATABLE_EXT";
			break;
		case(XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT):
			return U"XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT";
			break;
		case(XR_RESULT_MAX_ENUM):
			return U"XR_RESULT_MAX_ENUM";
			break;

		default:
			return U"UNKNOWN_OPENXR_RESULT_CODE";

	}

}

const wchar* vwstr_toStrXrEnvBlendMode(u32 In) {
	switch (In) {
		case(XR_ENVIRONMENT_BLEND_MODE_OPAQUE):
			return U"XR_ENVIRONMENT_BLEND_MODE_OPAQUE";
			break;
		case(XR_ENVIRONMENT_BLEND_MODE_ADDITIVE):
			return U"XR_ENVIRONMENT_BLEND_MODE_ADDITIVE";
			break;
		case(XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND):
			return U"XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND";
			break;
		case(XR_ENVIRONMENT_BLEND_MODE_MAX_ENUM):
			return U"XR_ENVIRONMENT_BLEND_MODE_MAX_ENUM";
			break;

		default:
			return U"TOSTR_XR_ENV_BLEND_MODE_FAILED";

	}

}

const wchar* vwstr_toStrVkResult(i32 In) {
	switch (In) {
		case(VK_SUCCESS):
			return U"VK_SUCCESS";
			break;
		case(VK_NOT_READY):
			return U"VK_NOT_READY";
			break;
		case(VK_TIMEOUT):
			return U"VK_TIMEOUT";
			break;
		case(VK_EVENT_SET):
			return U"VK_EVENT_SET";
			break;
		case(VK_EVENT_RESET):
			return U"VK_EVENT_RESET";
			break;
		case(VK_INCOMPLETE):
			return U"VK_INCOMPLETE";
			break;
		case(VK_ERROR_OUT_OF_HOST_MEMORY):
			return U"VK_ERROR_OUT_OF_HOST_MEMORY";
			break;
		case(VK_ERROR_OUT_OF_DEVICE_MEMORY):
			return U"VK_ERROR_OUT_OF_DEVICE_MEMORY";
			break;
		case(VK_ERROR_INITIALIZATION_FAILED):
			return U"VK_ERROR_INITIALIZATION_FAILED";
			break;
		case(VK_ERROR_DEVICE_LOST):
			return U"VK_ERROR_DEVICE_LOST";
			break;
		case(VK_ERROR_MEMORY_MAP_FAILED):
			return U"VK_ERROR_MEMORY_MAP_FAILED";
			break;
		case(VK_ERROR_LAYER_NOT_PRESENT):
			return U"VK_ERROR_LAYER_NOT_PRESENT";
			break;
		case(VK_ERROR_EXTENSION_NOT_PRESENT):
			return U"VK_ERROR_EXTENSION_NOT_PRESENT";
			break;
		case(VK_ERROR_FEATURE_NOT_PRESENT):
			return U"VK_ERROR_FEATURE_NOT_PRESENT";
			break;
		case(VK_ERROR_INCOMPATIBLE_DRIVER):
			return U"VK_ERROR_INCOMPATIBLE_DRIVER";
			break;
		case(VK_ERROR_TOO_MANY_OBJECTS):
			return U"VK_ERROR_TOO_MANY_OBJECTS";
			break;
		case(VK_ERROR_FORMAT_NOT_SUPPORTED):
			return U"VK_ERROR_FORMAT_NOT_SUPPORTED";
			break;
		case(VK_ERROR_FRAGMENTED_POOL):
			return U"VK_ERROR_FRAGMENTED_POOU";
			break;
		case(VK_ERROR_UNKNOWN):
			return U"VK_ERROR_UNKNOWN";
			break;
		case(VK_ERROR_OUT_OF_POOL_MEMORY):
			return U"VK_ERROR_OUT_OF_POOL_MEMORY or VK_ERROR_OUT_OF_POOL_MEMORY_KHR";
			break;
		case(VK_ERROR_INVALID_EXTERNAL_HANDLE):
			return U"VK_ERROR_INVALID_EXTERNAL_HANDLE or VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR";
			break;
		case(VK_ERROR_FRAGMENTATION):
			return U"VK_ERROR_FRAGMENTATION or VK_ERROR_FRAGMENTATION_EXT";
			break;
		case(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS):
			return U"VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS or VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR or VK_ERROR_INVALID_DEVICE_ADDRESS_EXT";
			break;
		case(VK_PIPELINE_COMPILE_REQUIRED):
			return U"VK_PIPELINE_COMPILE_REQUIRED or VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT or VK_PIPELINE_COMPILE_REQUIRED_EXT";
			break;
		case(VK_ERROR_SURFACE_LOST_KHR):
			return U"VK_ERROR_SURFACE_LOST_KHR";
			break;
		case(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR):
			return U"VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
			break;
		case(VK_SUBOPTIMAL_KHR):
			return U"VK_SUBOPTIMAL_KHR";
			break;
		case(VK_ERROR_OUT_OF_DATE_KHR):
			return U"VK_ERROR_OUT_OF_DATE_KHR";
			break;
		case(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR):
			return U"VK_ERROR_INCOMPATIBLE_DISPLAY_KHR";
			break;
		case(VK_ERROR_VALIDATION_FAILED_EXT):
			return U"VK_ERROR_VALIDATION_FAILED_EXT";
			break;
		case(VK_ERROR_INVALID_SHADER_NV):
			return U"VK_ERROR_INVALID_SHADER_NV";
			break;
		case(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR):
			return U"VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR";
			break;
		case(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT):
			return U"VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT";
			break;
		case(VK_ERROR_NOT_PERMITTED_KHR):
			return U"VK_ERROR_NOT_PERMITTED_KHR or VK_ERROR_NOT_PERMITTED_EXT";
			break;
		case(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT):
			return U"VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT";
			break;
		case(VK_THREAD_IDLE_KHR):
			return U"VK_THREAD_IDLE_KHR";
			break;
		case(VK_THREAD_DONE_KHR):
			return U"VK_THREAD_DONE_KHR";
			break;
		case(VK_OPERATION_DEFERRED_KHR):
			return U"VK_OPERATION_DEFERRED_KHR";
			break;
		case(VK_OPERATION_NOT_DEFERRED_KHR):
			return U"VK_OPERATION_NOT_DEFERRED_KHR";
			break;
		case(VK_ERROR_COMPRESSION_EXHAUSTED_EXT):
			return U"VK_ERROR_COMPRESSION_EXHAUSTED_EXT";
			break;
		case(VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT):
			return U"VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT";
			break;
		case(VK_RESULT_MAX_ENUM):
			return U"VK_RESULT_MAX_ENUM";
			break;
		default:
			return U"unknown_vk_result";
			//                TODO(V): Print the actuall integer value to console

	}

}

const wchar* vwstr_toStrVkFormat(i32 In) {
	switch (In) {
		case(VK_FORMAT_UNDEFINED):
			return U"VK_FORMAT_UNDEFINED";
			break;
		case(VK_FORMAT_R4G4_UNORM_PACK8):
			return U"VK_FORMAT_R4G4_UNORM_PACK8";
			break;
		case(VK_FORMAT_R4G4B4A4_UNORM_PACK16):
			return U"VK_FORMAT_R4G4B4A4_UNORM_PACK16";
			break;
		case(VK_FORMAT_B4G4R4A4_UNORM_PACK16):
			return U"VK_FORMAT_B4G4R4A4_UNORM_PACK16";
			break;
		case(VK_FORMAT_R5G6B5_UNORM_PACK16):
			return U"VK_FORMAT_R5G6B5_UNORM_PACK16";
			break;
		case(VK_FORMAT_B5G6R5_UNORM_PACK16):
			return U"VK_FORMAT_B5G6R5_UNORM_PACK16";
			break;
		case(VK_FORMAT_R5G5B5A1_UNORM_PACK16):
			return U"VK_FORMAT_R5G5B5A1_UNORM_PACK16";
			break;
		case(VK_FORMAT_B5G5R5A1_UNORM_PACK16):
			return U"VK_FORMAT_B5G5R5A1_UNORM_PACK16";
			break;
		case(VK_FORMAT_A1R5G5B5_UNORM_PACK16):
			return U"VK_FORMAT_A1R5G5B5_UNORM_PACK16";
			break;
		case(VK_FORMAT_R8_UNORM):
			return U"VK_FORMAT_R8_UNORM";
			break;
		case(VK_FORMAT_R8_SNORM):
			return U"VK_FORMAT_R8_SNORM";
			break;
		case(VK_FORMAT_R8_USCALED):
			return U"VK_FORMAT_R8_USCALED";
			break;
		case(VK_FORMAT_R8_SSCALED):
			return U"VK_FORMAT_R8_SSCALED";
			break;
		case(VK_FORMAT_R8_UINT):
			return U"VK_FORMAT_R8_UINT";
			break;
		case(VK_FORMAT_R8_SINT):
			return U"VK_FORMAT_R8_SINT";
			break;
		case(VK_FORMAT_R8_SRGB):
			return U"VK_FORMAT_R8_SRGB";
			break;
		case(VK_FORMAT_R8G8_UNORM):
			return U"VK_FORMAT_R8G8_UNORM";
			break;
		case(VK_FORMAT_R8G8_SNORM):
			return U"VK_FORMAT_R8G8_SNORM";
			break;
		case(VK_FORMAT_R8G8_USCALED):
			return U"VK_FORMAT_R8G8_USCALED";
			break;
		case(VK_FORMAT_R8G8_SSCALED):
			return U"VK_FORMAT_R8G8_SSCALED";
			break;
		case(VK_FORMAT_R8G8_UINT):
			return U"VK_FORMAT_R8G8_UINT";
			break;
		case(VK_FORMAT_R8G8_SINT):
			return U"VK_FORMAT_R8G8_SINT";
			break;
		case(VK_FORMAT_R8G8_SRGB):
			return U"VK_FORMAT_R8G8_SRGB";
			break;
		case(VK_FORMAT_R8G8B8_UNORM):
			return U"VK_FORMAT_R8G8B8_UNORM";
			break;
		case(VK_FORMAT_R8G8B8_SNORM):
			return U"VK_FORMAT_R8G8B8_SNORM";
			break;
		case(VK_FORMAT_R8G8B8_USCALED):
			return U"VK_FORMAT_R8G8B8_USCALED";
			break;
		case(VK_FORMAT_R8G8B8_SSCALED):
			return U"VK_FORMAT_R8G8B8_SSCALED";
			break;
		case(VK_FORMAT_R8G8B8_UINT):
			return U"VK_FORMAT_R8G8B8_UINT";
			break;
		case(VK_FORMAT_R8G8B8_SINT):
			return U"VK_FORMAT_R8G8B8_SINT";
			break;
		case(VK_FORMAT_R8G8B8_SRGB):
			return U"VK_FORMAT_R8G8B8_SRGB";
			break;
		case(VK_FORMAT_B8G8R8_UNORM):
			return U"VK_FORMAT_B8G8R8_UNORM";
			break;
		case(VK_FORMAT_B8G8R8_SNORM):
			return U"VK_FORMAT_B8G8R8_SNORM";
			break;
		case(VK_FORMAT_B8G8R8_USCALED):
			return U"VK_FORMAT_B8G8R8_USCALED";
			break;
		case(VK_FORMAT_B8G8R8_SSCALED):
			return U"VK_FORMAT_B8G8R8_SSCALED";
			break;
		case(VK_FORMAT_B8G8R8_UINT):
			return U"VK_FORMAT_B8G8R8_UINT";
			break;
		case(VK_FORMAT_B8G8R8_SINT):
			return U"VK_FORMAT_B8G8R8_SINT";
			break;
		case(VK_FORMAT_B8G8R8_SRGB):
			return U"VK_FORMAT_B8G8R8_SRGB";
			break;
		case(VK_FORMAT_R8G8B8A8_UNORM):
			return U"VK_FORMAT_R8G8B8A8_UNORM";
			break;
		case(VK_FORMAT_R8G8B8A8_SNORM):
			return U"VK_FORMAT_R8G8B8A8_SNORM";
			break;
		case(VK_FORMAT_R8G8B8A8_USCALED):
			return U"VK_FORMAT_R8G8B8A8_USCALED";
			break;
		case(VK_FORMAT_R8G8B8A8_SSCALED):
			return U"VK_FORMAT_R8G8B8A8_SSCALED";
			break;
		case(VK_FORMAT_R8G8B8A8_UINT):
			return U"VK_FORMAT_R8G8B8A8_UINT";
			break;
		case(VK_FORMAT_R8G8B8A8_SINT):
			return U"VK_FORMAT_R8G8B8A8_SINT";
			break;
		case(VK_FORMAT_R8G8B8A8_SRGB):
			return U"VK_FORMAT_R8G8B8A8_SRGB";
			break;
		case(VK_FORMAT_B8G8R8A8_UNORM):
			return U"VK_FORMAT_B8G8R8A8_UNORM";
			break;
		case(VK_FORMAT_B8G8R8A8_SNORM):
			return U"VK_FORMAT_B8G8R8A8_SNORM";
			break;
		case(VK_FORMAT_B8G8R8A8_USCALED):
			return U"VK_FORMAT_B8G8R8A8_USCALED";
			break;
		case(VK_FORMAT_B8G8R8A8_SSCALED):
			return U"VK_FORMAT_B8G8R8A8_SSCALED";
			break;
		case(VK_FORMAT_B8G8R8A8_UINT):
			return U"VK_FORMAT_B8G8R8A8_UINT";
			break;
		case(VK_FORMAT_B8G8R8A8_SINT):
			return U"VK_FORMAT_B8G8R8A8_SINT";
			break;
		case(VK_FORMAT_B8G8R8A8_SRGB):
			return U"VK_FORMAT_B8G8R8A8_SRGB";
			break;
		case(VK_FORMAT_A8B8G8R8_UNORM_PACK32):
			return U"VK_FORMAT_A8B8G8R8_UNORM_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_SNORM_PACK32):
			return U"VK_FORMAT_A8B8G8R8_SNORM_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_USCALED_PACK32):
			return U"VK_FORMAT_A8B8G8R8_USCALED_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_SSCALED_PACK32):
			return U"VK_FORMAT_A8B8G8R8_SSCALED_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_UINT_PACK32):
			return U"VK_FORMAT_A8B8G8R8_UINT_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_SINT_PACK32):
			return U"VK_FORMAT_A8B8G8R8_SINT_PACK32";
			break;
		case(VK_FORMAT_A8B8G8R8_SRGB_PACK32):
			return U"VK_FORMAT_A8B8G8R8_SRGB_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_UNORM_PACK32):
			return U"VK_FORMAT_A2R10G10B10_UNORM_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_SNORM_PACK32):
			return U"VK_FORMAT_A2R10G10B10_SNORM_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_USCALED_PACK32):
			return U"VK_FORMAT_A2R10G10B10_USCALED_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_SSCALED_PACK32):
			return U"VK_FORMAT_A2R10G10B10_SSCALED_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_UINT_PACK32):
			return U"VK_FORMAT_A2R10G10B10_UINT_PACK32";
			break;
		case(VK_FORMAT_A2R10G10B10_SINT_PACK32):
			return U"VK_FORMAT_A2R10G10B10_SINT_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_UNORM_PACK32):
			return U"VK_FORMAT_A2B10G10R10_UNORM_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_SNORM_PACK32):
			return U"VK_FORMAT_A2B10G10R10_SNORM_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_USCALED_PACK32):
			return U"VK_FORMAT_A2B10G10R10_USCALED_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_SSCALED_PACK32):
			return U"VK_FORMAT_A2B10G10R10_SSCALED_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_UINT_PACK32):
			return U"VK_FORMAT_A2B10G10R10_UINT_PACK32";
			break;
		case(VK_FORMAT_A2B10G10R10_SINT_PACK32):
			return U"VK_FORMAT_A2B10G10R10_SINT_PACK32";
			break;
		case(VK_FORMAT_R16_UNORM):
			return U"VK_FORMAT_R16_UNORM";
			break;
		case(VK_FORMAT_R16_SNORM):
			return U"VK_FORMAT_R16_SNORM";
			break;
		case(VK_FORMAT_R16_USCALED):
			return U"VK_FORMAT_R16_USCALED";
			break;
		case(VK_FORMAT_R16_SSCALED):
			return U"VK_FORMAT_R16_SSCALED";
			break;
		case(VK_FORMAT_R16_UINT):
			return U"VK_FORMAT_R16_UINT";
			break;
		case(VK_FORMAT_R16_SINT):
			return U"VK_FORMAT_R16_SINT";
			break;
		case(VK_FORMAT_R16_SFLOAT):
			return U"VK_FORMAT_R16_SFLOAT";
			break;
		case(VK_FORMAT_R16G16_UNORM):
			return U"VK_FORMAT_R16G16_UNORM";
			break;
		case(VK_FORMAT_R16G16_SNORM):
			return U"VK_FORMAT_R16G16_SNORM";
			break;
		case(VK_FORMAT_R16G16_USCALED):
			return U"VK_FORMAT_R16G16_USCALED";
			break;
		case(VK_FORMAT_R16G16_SSCALED):
			return U"VK_FORMAT_R16G16_SSCALED";
			break;
		case(VK_FORMAT_R16G16_UINT):
			return U"VK_FORMAT_R16G16_UINT";
			break;
		case(VK_FORMAT_R16G16_SINT):
			return U"VK_FORMAT_R16G16_SINT";
			break;
		case(VK_FORMAT_R16G16_SFLOAT):
			return U"VK_FORMAT_R16G16_SFLOAT";
			break;
		case(VK_FORMAT_R16G16B16_UNORM):
			return U"VK_FORMAT_R16G16B16_UNORM";
			break;
		case(VK_FORMAT_R16G16B16_SNORM):
			return U"VK_FORMAT_R16G16B16_SNORM";
			break;
		case(VK_FORMAT_R16G16B16_USCALED):
			return U"VK_FORMAT_R16G16B16_USCALED";
			break;
		case(VK_FORMAT_R16G16B16_SSCALED):
			return U"VK_FORMAT_R16G16B16_SSCALED";
			break;
		case(VK_FORMAT_R16G16B16_UINT):
			return U"VK_FORMAT_R16G16B16_UINT";
			break;
		case(VK_FORMAT_R16G16B16_SINT):
			return U"VK_FORMAT_R16G16B16_SINT";
			break;
		case(VK_FORMAT_R16G16B16_SFLOAT):
			return U"VK_FORMAT_R16G16B16_SFLOAT";
			break;
		case(VK_FORMAT_R16G16B16A16_UNORM):
			return U"VK_FORMAT_R16G16B16A16_UNORM";
			break;
		case(VK_FORMAT_R16G16B16A16_SNORM):
			return U"VK_FORMAT_R16G16B16A16_SNORM";
			break;
		case(VK_FORMAT_R16G16B16A16_USCALED):
			return U"VK_FORMAT_R16G16B16A16_USCALED";
			break;
		case(VK_FORMAT_R16G16B16A16_SSCALED):
			return U"VK_FORMAT_R16G16B16A16_SSCALED";
			break;
		case(VK_FORMAT_R16G16B16A16_UINT):
			return U"VK_FORMAT_R16G16B16A16_UINT";
			break;
		case(VK_FORMAT_R16G16B16A16_SINT):
			return U"VK_FORMAT_R16G16B16A16_SINT";
			break;
		case(VK_FORMAT_R16G16B16A16_SFLOAT):
			return U"VK_FORMAT_R16G16B16A16_SFLOAT";
			break;
		case(VK_FORMAT_R32_UINT):
			return U"VK_FORMAT_R32_UINT";
			break;
		case(VK_FORMAT_R32_SINT):
			return U"VK_FORMAT_R32_SINT";
			break;
		case(VK_FORMAT_R32_SFLOAT):
			return U"VK_FORMAT_R32_SFLOAT";
			break;
		case(VK_FORMAT_R32G32_UINT):
			return U"VK_FORMAT_R32G32_UINT";
			break;
		case(VK_FORMAT_R32G32_SINT):
			return U"VK_FORMAT_R32G32_SINT";
			break;
		case(VK_FORMAT_R32G32_SFLOAT):
			return U"VK_FORMAT_R32G32_SFLOAT";
			break;
		case(VK_FORMAT_R32G32B32_UINT):
			return U"VK_FORMAT_R32G32B32_UINT";
			break;
		case(VK_FORMAT_R32G32B32_SINT):
			return U"VK_FORMAT_R32G32B32_SINT";
			break;
		case(VK_FORMAT_R32G32B32_SFLOAT):
			return U"VK_FORMAT_R32G32B32_SFLOAT";
			break;
		case(VK_FORMAT_R32G32B32A32_UINT):
			return U"VK_FORMAT_R32G32B32A32_UINT";
			break;
		case(VK_FORMAT_R32G32B32A32_SINT):
			return U"VK_FORMAT_R32G32B32A32_SINT";
			break;
		case(VK_FORMAT_R32G32B32A32_SFLOAT):
			return U"VK_FORMAT_R32G32B32A32_SFLOAT";
			break;
		case(VK_FORMAT_R64_UINT):
			return U"VK_FORMAT_R64_UINT";
			break;
		case(VK_FORMAT_R64_SINT):
			return U"VK_FORMAT_R64_SINT";
			break;
		case(VK_FORMAT_R64_SFLOAT):
			return U"VK_FORMAT_R64_SFLOAT";
			break;
		case(VK_FORMAT_R64G64_UINT):
			return U"VK_FORMAT_R64G64_UINT";
			break;
		case(VK_FORMAT_R64G64_SINT):
			return U"VK_FORMAT_R64G64_SINT";
			break;
		case(VK_FORMAT_R64G64_SFLOAT):
			return U"VK_FORMAT_R64G64_SFLOAT";
			break;
		case(VK_FORMAT_R64G64B64_UINT):
			return U"VK_FORMAT_R64G64B64_UINT";
			break;
		case(VK_FORMAT_R64G64B64_SINT):
			return U"VK_FORMAT_R64G64B64_SINT";
			break;
		case(VK_FORMAT_R64G64B64_SFLOAT):
			return U"VK_FORMAT_R64G64B64_SFLOAT";
			break;
		case(VK_FORMAT_R64G64B64A64_UINT):
			return U"VK_FORMAT_R64G64B64A64_UINT";
			break;
		case(VK_FORMAT_R64G64B64A64_SINT):
			return U"VK_FORMAT_R64G64B64A64_SINT";
			break;
		case(VK_FORMAT_R64G64B64A64_SFLOAT):
			return U"VK_FORMAT_R64G64B64A64_SFLOAT";
			break;
		case(VK_FORMAT_B10G11R11_UFLOAT_PACK32):
			return U"VK_FORMAT_B10G11R11_UFLOAT_PACK32";
			break;
		case(VK_FORMAT_E5B9G9R9_UFLOAT_PACK32):
			return U"VK_FORMAT_E5B9G9R9_UFLOAT_PACK32";
			break;
		case(VK_FORMAT_D16_UNORM):
			return U"VK_FORMAT_D16_UNORM";
			break;
		case(VK_FORMAT_X8_D24_UNORM_PACK32):
			return U"VK_FORMAT_X8_D24_UNORM_PACK32";
			break;
		case(VK_FORMAT_D32_SFLOAT):
			return U"VK_FORMAT_D32_SFLOAT";
			break;
		case(VK_FORMAT_S8_UINT):
			return U"VK_FORMAT_S8_UINT";
			break;
		case(VK_FORMAT_D16_UNORM_S8_UINT):
			return U"VK_FORMAT_D16_UNORM_S8_UINT";
			break;
		case(VK_FORMAT_D24_UNORM_S8_UINT):
			return U"VK_FORMAT_D24_UNORM_S8_UINT";
			break;
		case(VK_FORMAT_D32_SFLOAT_S8_UINT):
			return U"VK_FORMAT_D32_SFLOAT_S8_UINT";
			break;
		case(VK_FORMAT_BC1_RGB_UNORM_BLOCK):
			return U"VK_FORMAT_BC1_RGB_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC1_RGB_SRGB_BLOCK):
			return U"VK_FORMAT_BC1_RGB_SRGB_BLOCK";
			break;
		case(VK_FORMAT_BC1_RGBA_UNORM_BLOCK):
			return U"VK_FORMAT_BC1_RGBA_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC1_RGBA_SRGB_BLOCK):
			return U"VK_FORMAT_BC1_RGBA_SRGB_BLOCK";
			break;
		case(VK_FORMAT_BC2_UNORM_BLOCK):
			return U"VK_FORMAT_BC2_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC2_SRGB_BLOCK):
			return U"VK_FORMAT_BC2_SRGB_BLOCK";
			break;
		case(VK_FORMAT_BC3_UNORM_BLOCK):
			return U"VK_FORMAT_BC3_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC3_SRGB_BLOCK):
			return U"VK_FORMAT_BC3_SRGB_BLOCK";
			break;
		case(VK_FORMAT_BC4_UNORM_BLOCK):
			return U"VK_FORMAT_BC4_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC4_SNORM_BLOCK):
			return U"VK_FORMAT_BC4_SNORM_BLOCK";
			break;
		case(VK_FORMAT_BC5_UNORM_BLOCK):
			return U"VK_FORMAT_BC5_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC5_SNORM_BLOCK):
			return U"VK_FORMAT_BC5_SNORM_BLOCK";
			break;
		case(VK_FORMAT_BC6H_UFLOAT_BLOCK):
			return U"VK_FORMAT_BC6H_UFLOAT_BLOCK";
			break;
		case(VK_FORMAT_BC6H_SFLOAT_BLOCK):
			return U"VK_FORMAT_BC6H_SFLOAT_BLOCK";
			break;
		case(VK_FORMAT_BC7_UNORM_BLOCK):
			return U"VK_FORMAT_BC7_UNORM_BLOCK";
			break;
		case(VK_FORMAT_BC7_SRGB_BLOCK):
			return U"VK_FORMAT_BC7_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK):
			return U"VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK";
			break;
		case(VK_FORMAT_EAC_R11_UNORM_BLOCK):
			return U"VK_FORMAT_EAC_R11_UNORM_BLOCK";
			break;
		case(VK_FORMAT_EAC_R11_SNORM_BLOCK):
			return U"VK_FORMAT_EAC_R11_SNORM_BLOCK";
			break;
		case(VK_FORMAT_EAC_R11G11_UNORM_BLOCK):
			return U"VK_FORMAT_EAC_R11G11_UNORM_BLOCK";
			break;
		case(VK_FORMAT_EAC_R11G11_SNORM_BLOCK):
			return U"VK_FORMAT_EAC_R11G11_SNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_4x4_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_4x4_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_4x4_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_4x4_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_5x4_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_5x4_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_5x4_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_5x4_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_5x5_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_5x5_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_5x5_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_5x5_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_6x5_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_6x5_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_6x5_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_6x5_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_6x6_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_6x6_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_6x6_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_6x6_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x5_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_8x5_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x5_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_8x5_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x6_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_8x6_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x6_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_8x6_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x8_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_8x8_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_8x8_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_8x8_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x5_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_10x5_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x5_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_10x5_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x6_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_10x6_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x6_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_10x6_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x8_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_10x8_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x8_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_10x8_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x10_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_10x10_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_10x10_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_10x10_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_12x10_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_12x10_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_12x10_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_12x10_SRGB_BLOCK";
			break;
		case(VK_FORMAT_ASTC_12x12_UNORM_BLOCK):
			return U"VK_FORMAT_ASTC_12x12_UNORM_BLOCK";
			break;
		case(VK_FORMAT_ASTC_12x12_SRGB_BLOCK):
			return U"VK_FORMAT_ASTC_12x12_SRGB_BLOCK";
			break;
		case(VK_FORMAT_G8B8G8R8_422_UNORM):
			return U"VK_FORMAT_G8B8G8R8_422_UNORM or VK_FORMAT_G8B8G8R8_422_UNORM_KHR";
			break;
		case(VK_FORMAT_B8G8R8G8_422_UNORM):
			return U"VK_FORMAT_B8G8R8G8_422_UNORM or VK_FORMAT_B8G8R8G8_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM):
			return U"VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM or VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8R8_2PLANE_420_UNORM):
			return U"VK_FORMAT_G8_B8R8_2PLANE_420_UNORM or VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM):
			return U"VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM or VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8R8_2PLANE_422_UNORM):
			return U"VK_FORMAT_G8_B8R8_2PLANE_422_UNORM or VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM):
			return U"VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM or VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR";
			break;
		case(VK_FORMAT_R10X6_UNORM_PACK16):
			return U"VK_FORMAT_R10X6_UNORM_PACK16 or VK_FORMAT_R10X6_UNORM_PACK16_KHR";
			break;
		case(VK_FORMAT_R10X6G10X6_UNORM_2PACK16):
			return U"VK_FORMAT_R10X6G10X6_UNORM_2PACK16 or VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR";
			break;
		case(VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16):
			return U"VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 or VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16):
			return U"VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 or VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16):
			return U"VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 or VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_R12X4_UNORM_PACK16):
			return U"VK_FORMAT_R12X4_UNORM_PACK16 or VK_FORMAT_R12X4_UNORM_PACK16_KHR";
			break;
		case(VK_FORMAT_R12X4G12X4_UNORM_2PACK16):
			return U"VK_FORMAT_R12X4G12X4_UNORM_2PACK16 or VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR";
			break;
		case(VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16):
			return U"VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16 or VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16):
			return U"VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 or VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16):
			return U"VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 or VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR";
			break;
		case(VK_FORMAT_G16B16G16R16_422_UNORM):
			return U"VK_FORMAT_G16B16G16R16_422_UNORM or VK_FORMAT_G16B16G16R16_422_UNORM_KHR";
			break;
		case(VK_FORMAT_B16G16R16G16_422_UNORM):
			return U"VK_FORMAT_B16G16R16G16_422_UNORM or VK_FORMAT_B16G16R16G16_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM):
			return U"VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM or VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR";
			break;
		case(VK_FORMAT_G16_B16R16_2PLANE_420_UNORM):
			return U"VK_FORMAT_G16_B16R16_2PLANE_420_UNORM or VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR";
			break;
		case(VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM):
			return U"VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM or VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G16_B16R16_2PLANE_422_UNORM):
			return U"VK_FORMAT_G16_B16R16_2PLANE_422_UNORM or VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR";
			break;
		case(VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM):
			return U"VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM or VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR";
			break;
		case(VK_FORMAT_G8_B8R8_2PLANE_444_UNORM):
			return U"VK_FORMAT_G8_B8R8_2PLANE_444_UNORM or VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT";
			break;
		case(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16):
			return U"VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16 or VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT";
			break;
		case(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16):
			return U"VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16 or VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT";
			break;
		case(VK_FORMAT_G16_B16R16_2PLANE_444_UNORM):
			return U"VK_FORMAT_G16_B16R16_2PLANE_444_UNORM or VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT";
			break;
		case(VK_FORMAT_A4R4G4B4_UNORM_PACK16):
			return U"VK_FORMAT_A4R4G4B4_UNORM_PACK16 or VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT";
			break;
		case(VK_FORMAT_A4B4G4R4_UNORM_PACK16):
			return U"VK_FORMAT_A4B4G4R4_UNORM_PACK16 or VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT";
			break;
		case(VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK or VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK or VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK or VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK or VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK or VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK or VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK or VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK or VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK or VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK or VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK or VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK or VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK or VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK):
			return U"VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK or VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT";
			break;
		case(VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG";
			break;
		case(VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG):
			return U"VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG";
			break;
		case(VK_FORMAT_R16G16_S10_5_NV):
			return U"VK_FORMAT_R16G16_S10_5_NV";
			break;
		case(VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR):
			return U"VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR";
			break;
		case(VK_FORMAT_A8_UNORM_KHR):
			return U"VK_FORMAT_A8_UNORM_KHR";
			break;
		case(VK_FORMAT_MAX_ENUM):
			return U"VK_FORMAT_MAX_ENUM";
			break;

		default:
			return U"vkformat_tostr_error";

	}

}

#endif // VLIB_REMOVE_TOSTR_FUNC

VLIBPP_END
